logging:
  level:
    org.springframework.cloud.netflix.zuul.filters.post.SendErrorFilter: info
  file: "/logs/boot-admin-sample.log"  # 日志输出路径
server:
  port: 8040
eureka:
  username: hypertech-dev
  password: hypertech-dev
  instance:
    hostname: registry
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health #2.0后actuator的地址发生了变化
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
  client:
    service-url:
      defaultZone: http://${eureka.username}:${eureka.password}@registry:8761/eureka/
spring:
  mail:
    host: smtp.126.com
    username: a6038080
    password: Aa123456
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  rabbitmq:
    host: 192.168.0.88
    port: 5672
    username: guest
    password: guest
  security:
    user:
      name: admin
      password: ${MONITOR_SERVER_PASSWORD:admin}
  application:
    name: admin-server
  boot:
    admin:
      notify:
        mail:
          to: 641298213@qq.com
          from: a6038080@126.com
management:
  endpoints:
    web:
      exposure:
        include: "health,env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream"
      #include: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
  endpoint:
    health:
      show-details: always
turbine:
  aggregator:
    cluster-config: default
  cluster-name-expression: new String("default")
  app-config: config,gateway
ribbon:
  okhttp:
    enabled: true
  http:
    client:
      enabled: false
