eureka:
  username: hypertech-dev
  password: hypertech-dev
  instance:
    hostname: auth
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
  client:
    service-url:
      defaultZone: http://${eureka.username}:${eureka.password}@registry:8761/eureka/
spring:
  application:
    name: auth
  security:
    user:
      name: user
      password: password
      roles: USER
  freemarker:
    allow-request-override: false
    cache: true
    check-template-location: true
    charset: utf-8
    suffix: .ftl
    template-loader-path: classpath:/templates/
    content-type: text/html
    expose-spring-macro-helpers: false
  redis:
    port: 6379
    host: 192.168.0.88
    database: 1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/usermanagement?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 3000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 from DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      filter: stat,wall,log4j
      connection-properties: 'druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000'
server:
  port: 8081
ribbon:
  http:
    client:
      enabled: false
  okhttp:
    enabled: true
